#define WARP_SIZE 32
#define NTHREADS 1024
#define NWARPS_PER_BLOCK NTHREADS/WARP_SIZE
#define NANTENNAS 48
#define NPOL 2
#define NBEAMS 512
#define NACCUMULATE 16
#define NSAMPLES_PER_BLOCK (NACCUMULATE * NTHREADS/WARP_SIZE)
#define NSAMPLES (NSAMPLES_PER_BLOCK * 2)
#define NCHANNELS 1
#define TSAMP 0.000005
#define NITERATIONS 100
#define TEST_CORRECTNESS
